---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_zero
  product_name: chef
  product_version: latest
  data_bags_path: "data_bags"
  roles_path: "roles"
  environments_path: "environments"
  deprecations_as_errors: true
  client_rb:
    treat_deprecation_warnings_as_errors: true
    resource_cloning: false

platforms:
  - name: ubuntu-16.04
  - name: centos-7.4

suites:
  - name: default
    data_bags_path: "data_bags"
    encrypted_data_bag_secret_key_path: "vagrant_encrypted_data_bag_secret"
    attributes:
      dirsrv:
        use_yum_epel: true
    run_list:
      - recipe[dirsrv::_test_kitchen]
