name             'dirsrv'
maintainer       'Alan Willis'
maintainer_email 'alwillis@riotgames.com'
source_url       'https://github.com/RiotGamesCookbooks/dirsrv-cookbook'
license          'Apache v2.0'
description      'Installs and configures 389 Directory Server'
version          '1.0.0'
chef_version     '>= 12.14.89'

depends 'ldap', '~> 2'
depends 'hostsfile'

supports 'debian', '>= 8'
supports 'ubuntu', '>= 16.04'
supports 'centos', '>= 7'
supports 'redhat', '>= 7'
supports 'scientific', '>= 7'
supports 'oracle', '>= 7'
supports 'fedora', '>= 19'